name: deploy-car model

on: [push]

jobs:
  build:
    name: compute engine deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/carpricepred:latest .

      - name: Push
        run: |
          docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/carpricepred:latest

      - name: Configure docker to pull from gcr On VM
        run: |
          gcloud compute ssh $GCE_INSTANCE --zone $GCE_INSTANCE_ZONE  --command 'gcloud auth configure-docker'

      - name: Pull image
        run: |
          gcloud compute ssh $GCE_INSTANCE --zone $GCE_INSTANCE_ZONE  --command 'docker pull eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/carpricepred:latest'

      - name: Deploy image
        run: |
          gcloud compute ssh $GCE_INSTANCE --zone $GCE_INSTANCE_ZONE  --command 'docker tag eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/carpricepred:latest carpricepred:latest  && docker-compose up -d'
